[package]
name = "life"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rand = "0.9.2"
tracing = "*"
tracing-subscriber = "*"

[[example]]
name = "bacteria_simulation"
path = "examples/bacteria_simulation.rs"
