name: Rust Versions

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-versions:
    name: Test Rust Versions
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build